seem/config/routes.rb
Rails.application.routes.draw do
  devise_for :students, controllers: {
	  sessions:      'students/sessions',
	  passwords:     'students/passwords',
	  registrations: 'students/registrations'
	}
  devise_for :companies, controllers: {
  sessions:      'companies/sessions',
  passwords:     'companies/passwords',
  registrations: 'companies/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#top"
  get '/students/mypage' => 'students#my_page'
  get '/companies/mypage' => 'companies#my_page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/students' => 'students#index'
  get '/students/:id' => 'students#show'
  # get '/students/posts/new' => 'posts#new'
  # post '/students/posts' => 'posts#create'
  # get '/posts/new' => 'posts#new'
  # post '/posts' => 'posts#create'

  resources :posts
end

seem/app/controllers/students/confirmations_controller.rb
class Students::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

seem/app/controllers/students/omniauth_callbacks_controller.rb
class Students::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

seem/app/controllers/students/passwords_controller.rb
class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

seem/app/controllers/students/sessions_controller.rb
class Students::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

seem/app/controllers/students/unlocks_controller.rb
class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

seem/app/views/students/my_page.html.erb
<div class="container">
    <header class="header">
        <p class="change"><%= link_to "⇔", "/students/#{current_student.id}" %></p>
        <p class="head_title">seem</p>
        <p class="head_item">
            <%= link_to "新規投稿", '/posts/new' %>
            <%= link_to "ログアウト", destroy_student_session_path, method: :delete %>
        </p>
    </header>
    <div class="profiel">
        <div class="main_profiel">
            <p class="user_name"><%= current_student.name %></p>
            <p class="profiel_edit"><%= link_to "プロフィール編集", edit_student_registration_path %></p>
        </div>
        <div class="sub_profiel">
            <p class="sub_profiel_item">学年:<%= current_student.grade %></p>
            <p class="sub_profiel_item">学校名:<%= current_student.school %></p>
            <p class="sub_profiel_item">学部:<%= current_student.undergraduate %></p>
            <p class="sub_profiel_item">自己紹介:<%= current_student.self_introduction %></p>
            <p class="sub_profiel_item">希望勤務地:<%= current_student.work_location %></p>
            <p class="sub_profiel_item">趣味:<%= current_student.hobby %></p>
            <p class="sub_profiel_item">出身地:<%= current_student.birthplace %></p>
            <p class="sub_profiel_item">希望職種:<%= current_student.job_category %></p>
            <p class="sub_profiel_item">所属サークル:<%= current_student.circle %></p>
            <p class="sub_profiel_item">所属ゼミ:<%= current_student.seminar %></p>
            <p class="sub_profiel_item">出身高校:<%= current_student.high_school %></p>
            <p class="sub_profiel_item">部活:<%= current_student.club %></p>
            <p class="sub_profiel_item">生年月日:<%= current_student.birthday %></p>
            <p class="sub_profiel_item">アルバイト歴:<%= current_student.part_time_job %></p>
        </div>
    </div>
    <div class="flex">
        <% @posts.each do |post|%>
            <% if post.image? %>
                <%= link_to post_path(post) do %>
                    <p class="flex_item"><%= image_tag post.image.url(:thumb) %></p>
                <% end %>
           <% else %>
        　     <%= image_tag 'noimage.gif' %>
           <% end %>
       <% end %>
    </div>
</div>