config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'

  devise_for :students,controllers: {
	  sessions:      'students/sessions',
	  passwords:     'students/passwords',
	  registrations: 'students/registrations'
	}
  devise_for :companies, controllers: {
    sessions:      'companies/sessions',
    passwords:     'companies/passwords',
    registrations: 'companies/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#top"
  get '/students/mypage' => 'students#my_page'
  get '/companies/mypage' => 'companies#my_page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/students' => 'students#index'
  get '/students/:id' => 'students#show'
  # get '/students/posts/new' => 'posts#new'
  # post '/students/posts' => 'posts#create'
  # get '/posts/new' => 'posts#new'
  # post '/posts' => 'posts#create'

  resources :posts
  get 'students/rooms/show' => 'rooms#show'
  get 'companies/rooms/show' => 'rooms#show'
  mount ActionCable.server => '/cable'

end

app/models/chat.rb
class Chat < ApplicationRecord
	after_create_commit { ChatBroadcastJob.perform_later self }
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # has_many :posts, :sudents
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :stundent
    belongs_to :company
    mount_uploader :image, ImageUploader
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  #¥ belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender ])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :grade, :school, :undergraduate, :self_introduction, :work_location, :hobby, :birthplace, :job_category, :circle, :seminar, :high_school, :part_time_job, :club, :department, :image, :birthday, :student_id])
  end

  def after_sign_out_path_for resource
    root_path
  end 
 
  def after_sign_in_path_for(resource)
    case resource
    when Student
      students_mypage_path
    when Company
      companies_mypage_path
    end
  end


  # before_filter :configure_permitted_parameters, if: :devise_controller?

  # protected

  # def configure_permitted_parameters
  #   #strong parametersを設定し、usernameを許可
  #   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :password, :password_confirmation, :email, :gender) }
  # end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def my_page
      @user = Company.where(:id=> current_company.id)
      @posts = Post.where(:company_id=> @user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only:[:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, only: [:new]
  before_action :correct_company, only: [:edit, :update]
  before_action :correct_student, only: [:edit, :update]
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to students_mypage_path(current_student.id)
  end

  def show
  end

  def index
  end

  def edit   
  end

  def update
  end

private
  def set_post
    @post = current_student.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:text, :image, :company_id, :student_id)
  end

  # def correct_company
  #   post = Post.find(params[:id])
  #   if current_company.id != post.company.id
  #     redirect_to root_path
  #   end
  # end

  def correct_student
    post = Post.find(params[:id])
    if current_student.id != post.student.id
      redirect_to root_path
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @chats = Chat.all
  end
end

app/controllers/students/registrations_controller.rb
class Students::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

   def after_update_path_for(resource)
       students_mypage_path(resource)
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @search = Student.search(params[:q])
    @students = @search.result(distinct: true)
  end
  
  def my_page
      @user = Student.where(:id=> current_student.id)
      @posts = Post.where(:student_id=> @user)
  end

  def show
    @student = Student.find(params[:id])
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/chats/_chat.html.erb
<div class="chat">
  <p><%= chat.content %></p>
</div>

app/views/companies/index.html.erb
<div class="container">
	<%= search_form_for @search do |f| %>
	    <%= f.label :name_cont, "ユーザー検索" %>
		<%= f.search_field :name_cont %>
		<%= f.submit %>
	<% end %>
	<%= link_to "戻る", companies_mypage_path %>
	<p>検索結果</p>
	<% @students.each do |student| %>
	    <%= link_to student.name, "/students/#{student.id}" %>
	<% end %>
</div>

app/views/companies/my_page.html.erb
<div class="container">
	<header>	
		<p class="head_title">seem</p>
		<p class="head_item">
			<%= link_to "学生検索", students_path %>
			<%= link_to "ログアウト", destroy_company_session_path, method: :delete %>
		</p>
	</header>
	<div class="main_profiel">
		<p class="user_name"><%= current_company.company_name %></p>
		<p class="chat_room"><%= link_to "Let's Talk", 'rooms/show' %></p>
	</div>
</div>

app/views/companies/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れた方はこちら", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/home/top.html.erb
<div class="container">
	<p class="top_title">seem</p>
	<p class="sub_title">〜面接に革新を〜</p>
	<div class="new_user">
		<div class="session student_session">
			<p class="position">学生</p>
			<p class="sign_up student_sign_up"><%= link_to "新規登録", new_student_registration_path %></p>
			<p class="login studnt_login"><%= link_to "ログイン", new_student_session_path %></p>
		</div>
		<div class="session company_session">
			<p class="position">人事担当</p>
			<p class="sign_up resources_sign_up"><%= link_to "新規登録", new_company_registration_path %></p>
			<p class="login resources_login"><%= link_to "ログイン", new_company_session_path %></p>
		</div>
	</div>
	<div class="introduction">
		<div class="intro_area">
		    <p class="intro_title">seemとは?</p>
			<p class="intro_text">実績や職歴がない学生の就職活動を、画像の力でサポートします。 <br>
				学生時代にやってきたこと(サークル・学生団体・部活・インターン)の画像をマイページに投稿し、 <br> オリジナルのアルバムを面接官に見ていただきましょう。</p>
		</div>
		<div class="intro_area">
			<p class="intro_title">使い方</p>
			<p class="intro_text">1. seemに登録する</p>
			<p class="intro_text">2. 画像を投稿！</p>
			<p class="intro_text">3. QRコードを印刷し、履歴書もしくはESに貼る</p>
			<p class="intro_text">4. seemを使っている面接官にQRコードを読み取ってもらう</p>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<h1>投稿編集</h1>
<% if student_signed_in? %>
  <%= form_for (@post) do |f| %>
    <h2>本文</h2>
    <%= f.label :text %>
    <%= f.text_field :text %>
    <%= f.hidden_field :student_id, value: current_student.id %>
    <%= f.submit "保存する" %>
  <% end %>
  <%= link_to "戻る", students_mypage_path %>
<% elsif company_signed_in? %>
  <%= form_for (@post) do |f| %>
    <h2>本文</h2>
    <%= f.label :text %>
    <%= f.text_field :text %> 
    <%= f.hidden_field :company_id, value: current_company.id %>
    <%= f.submit "保存する" %>
  <% end %>
<%= link_to "戻る", companies_mypage_path %>
<% end %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= @post.text %></td>
    </tr>
  <% end %>
</tbody>

<% if student_signed_in? %>
  <%= link_to "戻る", students_mypage_path %>
<% elsif company_signed_in? %>
  <%= link_to "戻る", companies_mypage_path %>
<% end %>

app/views/posts/new.html.erb
<div class="container">

 <div class="new_post">
 <p class="new_post_msg">画像を投稿しましょう</p>
	 <%= form_for (@post) do |f| %>
	 <div class="new_post_image">
		  <%= f.label :画像 %>
		  <%= f.file_field :image %> 
	  </div>
	  <div class="new_post_text">
		  <%= f.label :説明 %>
		  <%= f.text_field :text %>
	  </div>
		  <%= f.hidden_field :student_id, value: current_student.id %>
		  <%= f.submit "投稿する" %>
	<% end %>


	<% if student_signed_in? %>
	  <%= link_to "戻る", students_mypage_path %>
	<% elsif company_signed_in? %>
	  <%= link_to "戻る", companies_mypage_path %>
	<% end %>
</div>

</div>

app/views/posts/show.html.erb
<div class="show">
    <div class="photo">
	    <% if @post.image? %>
		    <td><%= image_tag @post.image.url %></td>
		<% else %>
		　  <td><%= image_tag 'noimage.gif' %></td>
		<% end %>
	</div>
	<div class="textarea">
	    <p class="text"><%= @post.text %></p>
	</div>
    <% if student_signed_in? %>	
	    <p class="show_link delete"><%= link_to "削除", post_path(@post.id), method: :delete %></p>
	    <p class="show_link back"><%= link_to "戻る", :back %></p>
    <% else %>
        <p class="show_link back"><%= link_to "戻る", :back %></p>
    <% end %>
</div>

app/views/rooms/show.html.erb
<div class="container">
<header class="header">	
	<div class="chat_area">
		<h1 class="chat_title">Chat room</h1>
		<div id="chats", class="chat_area_item">
		  <%= render @chats %>
		</div>
		<form class="msg_form">
		  <input type="text" data-behavior="room_speaker" placeholder="メッセージを入力" class="field">
		</form>
	</div>
	<div class="field">
		<% if student_signed_in? %>
		  	<div class="chat_modoru"><%= link_to "戻る", students_mypage_path %></div>
		<% elsif company_signed_in? %>
		  	<div class="chat_modoru"><%= link_to "戻る", companies_mypage_path %></div>
		<% end %>
		
	</div>
</header>
</div>

app/views/students/index.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れてしまった方はこちら", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/students/job.html.erb
<body>
<section>
	<div class="job"></div>
	<div class="question"></div>
	<div class="question"></div>
</section>
<section>
	<div class="job"></div>
	<div class="question"></div>
	<div class="question"></div>
</section>
<section>
	<a href="#" data-reveal-id="myModal">Click Me For A Modal</a>

<div id="myModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <h2 id="modalTitle">Awesome. I have it.</h2>
  <p class="lead">Your couch.  It is mine.</p>
  <p>I'm a cool paragraph that lives inside of an even cooler modal. Wins!</p>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>
</section><p><a data-toggle="exampleModal8">Click me for a full-screen modal</a></p>

<div class="full reveal" id="exampleModal8" data-reveal>
  <p>OH I'M SO FUUUUL</p>
  <button class="close-button" data-close aria-label="Close reveal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

</body>

app/views/students/my_page.html.erb
<div class="container">
    <header class="header">
        <p class="change"><%= link_to "⇔", "/students/#{current_student.id}" %></p>
        <p class="head_title">seem</p>
        <p class="head_item">
            <%= link_to "新規投稿", '/posts/new' %>
            <%= link_to "ログアウト", destroy_student_session_path, method: :delete %>
        </p>
    </header>
    <div class="profiel">
        <div class="main_profiel">
            <p class="user_name"><%= current_student.name %></p>
            <p class="profiel_edit"><%= link_to "プロフィール編集", edit_student_registration_path %></p>
            <p class="chat_room"><%= link_to "Let's Talk", 'rooms/show' %></p>
        </div>
        <div class="sub_profiel">
            <p class="sub_profiel_item">学年:<%= current_student.grade %></p>
            <p class="sub_profiel_item">学校名:<%= current_student.school %></p>
            <p class="sub_profiel_item">学部:<%= current_student.undergraduate %></p>
            <p class="sub_profiel_item">自己紹介:<%= current_student.self_introduction %></p>
            <p class="sub_profiel_item">希望勤務地:<%= current_student.work_location %></p>
            <p class="sub_profiel_item">趣味:<%= current_student.hobby %></p>
            <p class="sub_profiel_item">出身地:<%= current_student.birthplace %></p>
            <p class="sub_profiel_item">希望職種:<%= current_student.job_category %></p>
            <p class="sub_profiel_item">所属サークル:<%= current_student.circle %></p>
            <p class="sub_profiel_item">所属ゼミ:<%= current_student.seminar %></p>
            <p class="sub_profiel_item">出身高校:<%= current_student.high_school %></p>
            <p class="sub_profiel_item">部活:<%= current_student.club %></p>
            <p class="sub_profiel_item">生年月日:<%= current_student.birthday %></p>
            <p class="sub_profiel_item">アルバイト歴:<%= current_student.part_time_job %></p>
        </div>
    </div>
    <div class="flex">
        <% @posts.each do |post|%>
            <% if post.image? %>
                <%= link_to post_path(post) do %>
                    <p class="flex_item"><%= image_tag post.image.url(:thumb) %></p>
                <% end %>
           <% else %>
        　     <%= image_tag 'noimage.gif' %>
           <% end %>
       <% end %>
    </div>
</div>

app/views/students/show.html.erb
<div class="container">
    <header class="header">
        <p><a data-toggle="exampleModal8" class="qr_btn">🔲</a></p>
        <div class="full reveal" id="exampleModal8" data-reveal>
            <p class="close"><a data-toggle="exampleModal8">close</a></p>
            <p class="print_msg">QRコードを印刷してください</p>
            <div class="qr_code"><%= qrcode_tag request.url, module_size: 7 %></div> 
            <button class="close-button" data-close aria-label="Close reveal" type="button">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <p class="head_title">seem</p>
            <p class="head_item">
                    <%= link_to "戻る", :back %>
            </p>
    </header>
    <div class="profiel">
        <div class="main_profiel">
            <p class="user_name"><%= @student.name %></p>
        </div>
        <div class="sub_profiel">
            <p class="sub_profiel_item">学年:<%= @student.grade %></p>
            <p class="sub_profiel_item">学校名:<%= @student.school %></p>
            <p class="sub_profiel_item">学部:<%= @student.undergraduate %></p>
            <p class="sub_profiel_item">自己紹介:<%= @student.self_introduction %></p>
            <p class="sub_profiel_item">希望勤務地:<%= @student.work_location %></p>
            <p class="sub_profiel_item">趣味:<%= @student.hobby %></p>
            <p class="sub_profiel_item">出身地:<%= @student.birthplace %></p>
            <p class="sub_profiel_item">希望職種:<%= @student.job_category %></p>
            <p class="sub_profiel_item">所属サークル:<%= @student.circle %></p>
            <p class="sub_profiel_item">所属ゼミ:<%= @student.seminar %></p>
            <p class="sub_profiel_item">出身高校:<%= @student.high_school %></p>
            <p class="sub_profiel_item">部活:<%= @student.club %></p>
            <p class="sub_profiel_item">生年月日:<%= @student.birthday %></p>
            <p class="sub_profiel_item">アルバイト歴:<%= @student.part_time_job %></p>
        </div>
        <div class="flex">
            <% @student.posts.each do |post|%>
                <% if post.image? %>
                    <%= link_to post_path(post) do %>
                        <div class="flex_item">
                　          <%= image_tag post.image.url(:thumb) %>
                        </div>
                    <% end %>
                <% else %>
            　      <%= image_tag 'noimage.gif' %>
                <% end %>
            <% end %>
         </div>
    </div>
</div>