seem/config/routes.rb
Rails.application.routes.draw do
  devise_for :students, controllers: {
	  sessions:      'students/sessions',
	  passwords:     'students/passwords',
	  registrations: 'students/registrations'
	}
  devise_for :companies, controllers: {
  sessions:      'companies/sessions',
  passwords:     'companies/passwords',
  registrations: 'companies/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#top"
  get '/students/mypage' => 'students#my_page'
  get '/companies/mypage' => 'companies#my_page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/students' => 'students#index'
  get '/students/:id' => 'students#show'
  # get '/students/posts/new' => 'posts#new'
  # post '/students/posts' => 'posts#create'
  # get '/posts/new' => 'posts#new'
  # post '/posts' => 'posts#create'

  resources :posts
end

seem/app/models/post.rb
class Post < ApplicationRecord
	belongs_to :student
	mount_uploader :image, ImageUploader
end

seem/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only:[:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, only: [:new]
  before_action :correct_company, only: [:edit, :update]
  before_action :correct_student, only: [:edit, :update]
  def new
    @post = Post.new
  end


  def create
    # binding.pry
    @post = Post.new(post_params)
    @post.save
    redirect_to students_mypage_path(current_student.id)
  end

  def show
  end

  def index
  end

  def edit
  end

  def update
  end

  def destroy
     @posts = Post.find(params[:id])
     @posts.destroy
     redirect_to students_mypage_path 
  end

private
  def set_post
    @post = current_student.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:text, :image, :student_id)
  end

  # def correct_company
  #   post = Post.find(params[:id])
  #   if current_company.id != post.company.id
  #     redirect_to root_path
  #   end
  # end

  def correct_student
    post = Post.find(params[:id])
    if current_student.id != post.student.id
      redirect_to root_path
    end
  end
end

seem/app/helpers/posts_helper.rb
module PostsHelper
end

seem/app/views/posts/new.html.erb
<div class="container">
	<div class="new_post">
	    <p class="new_post_msg">画像を投稿しましょう</p>
		<%= form_for (@post) do |f| %>
		    <div class="new_post_image">
			    <%= f.label :画像 %>
			    <%= f.file_field :image %> 
		    </div>
		    <div class="new_post_text">
			    <%= f.label :説明 %>
			    <%= f.text_field :text %>
		    </div>
			    <%= f.hidden_field :student_id, value: current_student.id %>
			    <%= f.submit "投稿する" %>
		<% end %>
		<% if student_signed_in? %>
		    <%= link_to "戻る", students_mypage_path %>
		<% elsif company_signed_in? %>
		    <%= link_to "戻る", companies_mypage_path %>
		<% end %>
	</div>
</div>